url: "https://github.com/willfantom/goverseerr/releases/download/$VERSION/overclirr-$VERSION-darwin-amd64.tar.gz"
tap: willfantom/homebrew-overclirr/overclirr.rb
branches: main
template: >
  class Overclirr < Formula
    desc     "Manage a Media Server from the CLI with Overseerr/OverCLIrr"
    homepage "$REPO_WEBSITE"
    version  "$STABLE_VERSION"
    url      "$STABLE_ASSET_URL"
    sha256   "$STABLE_ASSET_SHA256"


    def install
      prefix.install "overclirr"
    end
  end
